# Generated by Django 4.2.13 on 2025-02-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="difficulty_level",
            field=models.CharField(default="All Levels", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="course_materials/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.course",
                    ),
                ),
            ],
        ),
    ]
